<?

## init modules
$logon=$_MODS->Load('logon01','logon');
$var=$_MODS->Load('var01','var');
$order=$_MODS->Load('order01','order');
$to_refresh=$_MODS->Load('to_refresh01','to_refresh');
$banner=$_MODS->Load('banner01','banner');
//$catalog=$_MODS->Load('catalog01','catalog');
//$banners=$_MODS->Load('banners01','banners');
$pblc=$_MODS->Load('pblc01','pblc');
//$journal=$_MODS->Load('journal01','journal');
//$experts=$_MODS->Load('experts01','experts');
//$programm=$_MODS->Load('prg01','programm');
//$afisha=$_MODS->Load('afisha01','afisha');
//global $live;
//$live=$_MODS->Load('live01','live');
//$poll=$_MODS->Load('poll01','poll');
$page=$_MODS->Load('page01','page');
##

?>